DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER
(
    CUSTOMER_ID INT PRIMARY KEY
);

CREATE TABLE ACCOUNT
(
    ACCOUNT_ID         INT PRIMARY KEY,
    CUSTOMER_ID INT,
    foreign key (CUSTOMER_ID) references CUSTOMER(CUSTOMER_ID)
);



